### ISSUE TITLE
Add support for intermediate checkbox

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#11]
While we select all from the table header checkbox and deselect any of the checkboxes from the list then intermediate checkbox style is preferred. Ant design does have a clear explanation and also if the checkbox style will be like some customizable like in ant design that will be awesome.

Reference: https://ant.design/components/checkbox/#components-checkbox-demo-check-all

**Comment by NadavShaar** [comment]
I will "check" :) it out... Thanks.

**Comment by NadavShaar** [comment]
The indeterminate state has been added to the select all checkbox, thanks for the feedback.
