### ISSUE TITLE
Table pagination page input

### ISSUE THREAD

**Issue by stychu** [NadavShaar/react-grid-table#110]
Hi there,
It seems that table pagination input for current page is kinda not functional. 
If I select the text in the input and replace it with number that is in range of pages it will work. But I would rather expect it will work also whenever I press some number combination without selecting the input but currently it always goes automatically to the last page when I press a number or when I try to remove it it goes to 1 st page.

I think it should consider valid range input. 
For ex.
If I have 15 pages then inputting a value with focus on the input without the selection of its value:
1,2,3,4,5,6,7,8,9 will work
11,12,13,14,15 will work
16 and above will automatically set to 15
0 or less or invalid will set to 1

**Comment by NadavShaar** [comment]
Hi, the behavior of the input is intentional and was meant to keep you in range, if you have in the input value of 12 out of 15, and you'll enter numbers without replacing the value you'll be out of range.
