### ISSUE TITLE
Delete row/item

### ISSUE THREAD

**Issue by NChadwick22** [NadavShaar/react-grid-table#113]
Are there any near plans to support row (item) erasing?

**Comment by NadavShaar** [comment]
What do you mean? the table doesn't manage your data, you should be able to do it outside of it.

**Comment by NChadwick22** [comment]
I mean the client part of it, like editing. I didn't find anywhere in the documentation about a delete button (like other data grid libraries) and a call to a backend (ex.: API endpoint) and handling the response in order to delete that row from the DOM. Of course the server-side is responsible of the actual deletion of the item in the database but that is not what I am asking.
