### ISSUE TITLE
Debounce search for onRowsRequest

### ISSUE THREAD

**Issue by stychu** [NadavShaar/react-grid-table#116]
Seems like the `requestDebounceTimeout` is coupled with pagination and search is executed separately on every keystroke.
I need a custom search with debounce for the search so it executes the `onRowsRequest` call to my API only after user stops typing but I can't figure out how I could achieve this. Do you have any idea how to debounce the search?

**Comment by NadavShaar** [comment]
Can't you debounce the function that you pass to `onRowsRequest`?

**Comment by stychu** [comment]
@NadavShaar 

Tried debounce on the `onRowsRequest` but seems that the table doesn't render the data although the data comes in after the debounce occurs.

So I achieved the debounce on debouncing the search when user types in which I was looking for. But also I found a bug with the searchApi.

Bug seems to occur whenever you use `onRowsRequest` (async mode).
When you have `onRowsRequest` and you try to type the query doesn't trigger for the 1st letter. 
So if I type just `a` it won't trigger the fetch. If I then add `a` = `aa` then second `a` triggers the request.
Same happens when I delete text. If there are two letters `aa` and I remove one then this triggers the `onRowsRequest` but then when I delete the one single `a` it doesn't trigger the `onRowsRequest` where it should.

Here is demo code that I managed to pull with debounce of the search and also you can check the bug with one letter not triggering `onRowRequest`.
Also selecting the whole text and removing everything acts as a single letter remove and triggers the request.
If I uncomment line 27 and comment 28 then this triggers the fetch as it should (nasty hack).
You can also try to remove the custom Header component and see the internal search has the same problem.

https://codesandbox.io/s/react-grid-table-async-forked-g9qzod?file=/src/App.js


https://user-images.githubusercontent.com/9383657/212772214-ab457a8d-4748-4b55-a73f-e251b871a3c4.mov

**Comment by NadavShaar** [comment]
Hi again, i saw the demo and you're right, debouncing the search function is the way to go.
Regarding the bug you're referring to, it's not a bug it's intentional behavior, there's a prop: `minSearchChars` which controls how many chars the user will enter in order to trigger the search, and its defaults to `2`, you can change it to `1`  if you want to trigger the search for every char.

**Comment by stychu** [comment]
Ahh I see. Not very clear to understand from the first glance. Now I know, thanks!
