### ISSUE TITLE
Little improvement to sorting icon

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#12]
Near the download button, there is a three-dot icon that represents a similar approach to controlling columns. Rather than current icons just like below will suit better
![image](https://user-images.githubusercontent.com/3774827/95375275-1f50be00-08ff-11eb-95fd-9cdeee586a3d.png)

**Comment by NadavShaar** [comment]
Not sure what you mean about the sort icons can you clarify please?

**Comment by NadavShaar** [comment]
Updated, thanks.
