### ISSUE TITLE
export components

### ISSUE THREAD

**Issue by ilayofir** [NadavShaar/react-grid-table#16]
Would be nice to export all the components used by the table, so they would be usable via import.
This will allow customizations using the built in components, like switching the header and footer etc.

**Comment by shivapoudel** [comment]
I suggest exporting data in CSV format will be nice.

**Comment by shivapoudel** [comment]
@NadavShaar Is export feature in demo?

**Comment by NadavShaar** [comment]
The export for components is not the export for data as you refer to, and currently will not be implemented for the first release.
