### ISSUE TITLE
Support SCSS

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#23]
If we import this module into our project do allow us to import styles from the SCSS file so we can modify the variables.

**Comment by NadavShaar** [comment]
As far as i know you can import css files too no?

**Comment by shivapoudel** [comment]
I still want third-party CSS files to be a part of my final single CSS built with SASS. When you use module bundlers such as Webpack relying on `@import url(third-party.css)` is not a good option because you have to care about copying CSS files to the destination by yourself... It introduces an additional headache, especially, when your visual components styled with SASS are split into separate npm modules.

Importing CSS files from Sass doesn't include them into the bundled CSS file but just keep importing them as external CSS files which won't work in prod because we don't ship the `node_modules` in production :)

To long to read but go through this https://github.com/sass/node-sass/issues/2362

**Comment by NadavShaar** [comment]
As for now, we will not support SCSS.
