### ISSUE TITLE
How can I add a new person with add button in Header.jsx Sir!

### ISSUE THREAD

**Issue by lamtuankiet0901** [NadavShaar/react-grid-table#33]

**Comment by NadavShaar** [comment]
You'll be able to add your own custom buttons and functionality to the header using the headerRenderer prop.... Once the table will be published of course (should be next month), and i will add some codesandboxes for such use cases.

**Comment by lamtuankiet0901** [comment]
Thank you sir! How can I update when data has been changed Sir <3
