### ISSUE TITLE
Having hard time to install

### ISSUE THREAD

**Issue by RuiRitaYang** [NadavShaar/react-grid-table#35]
Hi,

This is Rui. I'm new to React and I'm trying to make an editable table for my web app. However, I'm having trouble using this lib. When I tried "npm install @nadavshaar/react-grid-table", it shows ERR: Not Found - GET https://registry.npmjs.org/@nadavshaar%2freact-grid-table - Not found.
The yarn install also does not work. 

Am I using the wrong way to utilize this lib? I'd be great if you would help or provide some suggestions!

Thanks in advance.

Regards,
-Rui

**Comment by NadavShaar** [comment]
Hey Rui.
Thanks for interesting in my table. 
This package is now in the last stages of development, and the reason you are getting an error is because it is not published yet to npm, but it will in the next week or two. 
Stay tuned, and have a good day!
