### ISSUE TITLE
Storybook is implemented?

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#37]
If storybook is implemented then please do share it so we can have a look, my friend :)

**Comment by shivapoudel** [comment]
Also when will this be available in the NPM repo, my friend :)

**Comment by NadavShaar** [comment]
Hi... storybook is implemented but we the stories are not ready yet.
About the availability, we are extending the development a bit to add support for async support too, so it will take some more time and there's still a bit of testing to do.
I want to believe that development will be done by the end of this month, and first release will be ready somewhere in the next month.
Thanks, and stay tuned.

**Comment by shivapoudel** [comment]
I tried to install this table component via npm through github branch but doing so only package.json and readme is extracted. Can you guide me some steps to install through GitHub until it is released in npm?

**Comment by NadavShaar** [comment]
As i wrote above: first release will be ready somewhere in the next month, only then the table will be published to npm.

**Comment by NadavShaar** [comment]
We decided to pass on storybook at the moment.
