### ISSUE TITLE
How to override Header component in the latest changes?

### ISSUE THREAD

**Issue by shivapoudel** [NadavShaar/react-grid-table#38]
After the merge of server-side branch to main, now `headerComponents` props is no longer accepting values. Is there any behavioral changes @ilayofir

**Comment by NadavShaar** [comment]
`components={{ Header: YourCustomComponent }}`

**Comment by NadavShaar** [comment]
We will update the docs soon.

**Comment by shivapoudel** [comment]
@NadavShaar thanks! That works great :)
