### ISSUE TITLE
Finalizing Select All

### ISSUE THREAD

**Issue by NadavShaar** [NadavShaar/react-grid-table#42]
Go over select all rows logic & documentation in regard to async.

**Comment by ilayofir** [comment]
select all is finished, with a small caveat - If using an a-sync flow with pagination, than supplying a page size or batch size that don't match each other might cause the table to request only part of the rows in the page. This means that the select all might not be able to select all the rows of the page.
An obvious fix is to match the page size as batch size via props. 
But I am thinking maybe we should do that by default..
It would mean that, if uncontrolled, the batch size will change whenever the page size changes.
@NadavShaar I can't decide if this is a good default behavior.

**Comment by NadavShaar** [comment]
@ilayofir please sync batch size and page size and disable "All" mode selection for async.

**Comment by ilayofir** [comment]
synced!
