### ISSUE TITLE
Passing isHeaderSticky=true, breaks column reordering.

### ISSUE THREAD

**Issue by ilayofir** [NadavShaar/react-grid-table#49]
Passing isHeaderSticky=true makes the column reordering behave strange.
Probably something to do with the cell headers position?

**Comment by NadavShaar** [comment]
@ilayofir i believe you meant Passing isHeaderSticky=**false** makes the column reordering behave strange.
And you're right, it's a positioning issue, or the lack of positioning, while not in sticky mode, the header cells now will be relative positioned which will fix the strange behavior.
