### ISSUE TITLE
Internal components - used props

### ISSUE THREAD

**Issue by NadavShaar** [NadavShaar/react-grid-table#51]
Use properties for internal components only from tableManager so it will be easier to use them from outside, this way the user will only have to make sure to pass them the tableManager object without any other arguments.

An example of such a use-case is when a user wants to add a button to the header component then he'll have to override all header but it would be possible to import the internal components like the search or the column visibility manager and implement them only with tableManager as props.

Do not remove the other arguments passed to the components since they can be used when the user would like to create a custom component (not the internal one).

**Comment by ilayofir** [comment]
added fallbacks to tableManager values in internal components + removed passing of these values in internal components
