### ISSUE TITLE
Urgent Help: How to use tableManager API out of the component by using useRef?

### ISSUE THREAD

**Issue by catrawalkar** [NadavShaar/react-grid-table#61]
I with to access tableManager API out of the gridTable component to programatically update table. How can I do that by using useRef??
Help would be much appreciated.

Also, best react table by far used. Thanks for tthis

**Comment by NadavShaar** [comment]
Hi...
Thanks for your interest...

To get the tableManager instance you can use the onLoad prop which will
give it to you once it's initialized, no need for ref.
Once it's ready, pass it to the highest component state that you want to
use it and from there you can use it from the state or pass it to
its children.

onLoad={tableManger => setTableManger(tableManger)}
or just:
onLoad={setTableManger}

Hope it helps.
Let me know how it goes... :)

**Comment by catrawalkar** [comment]
Hi, this was really helpful. Sorry, got busy in project so didn't reply but it was really helpful

**Comment by NadavShaar** [comment]
Glad to hear it.
