### ISSUE TITLE
Search API Issue

### ISSUE THREAD

**Issue by catrawalkar** [NadavShaar/react-grid-table#63]
Hello,

I am doing a remote api search using search element. I have given an attribute : minSearchChars = {5}

Ideally it should not trigger onRowsRequest I think.. but it is triggering onRowRequest. 

I am confused on how to implement search in this. I want to use minSearchChars too... Please help

**Comment by NadavShaar** [comment]
You are right after testing it was a bug.
Will be fixed soon in the next version `v0.2.1`.

**Comment by catrawalkar** [comment]
Hi, I see that you have pushed new version `v0.2.1` but when I type something in search it still calls onRowsRequest method even when entered characters < minSearchChars . Am I doing anything wrong?

**Comment by NadavShaar** [comment]
Hi again... You're right something went wrong with the last build, i'll
publish a fix soon.

**Comment by NadavShaar** [comment]
You can now get the fix in the new version v0.2.2.
