### ISSUE TITLE
Async not working.

### ISSUE THREAD

**Issue by ncminh** [NadavShaar/react-grid-table#68]
Re-produce steps:
1.Run the project in async mode.
2. Click on edit button in any row.
3. Edit data on that row.
4. Click the checked mark button.
5. Console showed errors like attached image.
![image](https://user-images.githubusercontent.com/11650871/113814507-f7ea8900-979b-11eb-8358-786b01e5dfa3.png)

**Comment by NadavShaar** [comment]
Hi..
There's no `setRows` function under `asyncApi`, please go over the docs.
If you are using the async version and you're getting the data from the server you probably want to update the edited data to the server and refetch that new data.
