### ISSUE TITLE
How can I add a button to download the table data in excel sheet?

### ISSUE THREAD

**Issue by catrawalkar** [NadavShaar/react-grid-table#69]
Is there any way I can give a download button which will download the data in csv format?

**Comment by NadavShaar** [comment]
Yes you can use the "components" prop to override the default component that you want the button to be part of.

**Comment by catrawalkar** [comment]
But is there any function which when called will download csv ?

**Comment by NadavShaar** [comment]
No you'll have to create the button with its logic and implement it in one
of the table's components
