### ISSUE TITLE
Pre-selected Data

### ISSUE THREAD

**Issue by zaweb** [NadavShaar/react-grid-table#73]
I've been using and enjoying react-grid-table. Thank you!

Question: When rows are generated, I would like some rows to be pre-checked depending on the contents of the row data. Is this possible? 

For example: Suppose I want to produce a table containing a list of cars that I own. Columns would be something like "Owned (checkbox)", "Brand", "Model", "Color", "Year", etc.

My row data has a key-value called "owned." If it's 'owned' is true, the row's "Owned" column checkbox is checked. If it's false, then it is not checked. 

Does this make sense? Is this possible?

Thank you!

-B

**Comment by NadavShaar** [comment]
Hi...
This can be done by initially passing the selected rows ids using the `selectedRowsIds` prop, whatever logic you apply to get the ids doesn't matter.

Demo:
https://codesandbox.io/s/rgt-initial-row-selection-7kc6f?file=/src/App.js

In my example, I'm initially selecting all the users that have `gender: 'Male` in the row data (`initialSelectedRows` ).
