### ISSUE TITLE
Pine more than one column

### ISSUE THREAD

**Issue by luisotavio756** [NadavShaar/react-grid-table#78]
In my application, I need pine more than the first column. 
Ex: 
Since the checkbox, I want pine the Username, and the FisrtName, and the LastName.. I could make this configurable?
Exists some workaround to make this?

Thanks!

**Comment by NadavShaar** [comment]
Sorry currently we support pinning only for the first and last columns, hopefully we can extend this feature in the future,but currently it's a limitation.
