### ISSUE TITLE
onRowsRequest called twice during initial load

### ISSUE THREAD

**Issue by kringo** [NadavShaar/react-grid-table#80]
Hi,

I'm using this example https://github.com/NadavShaar/react-grid-table#async-uncontrolled with an api and it works great however when i looked into console window, there is 2 calls going to the api during initial load.

Adding a console.log to onRowsRequest shows it's called twice, is it a bug or I'm doing something wrong?

SO had a suggestion for something related and removed strict mode, still no difference.

**Comment by ilayofir** [comment]
Hmm.. Are you specifying a batchSize?

**Comment by kringo** [comment]
I specify pageSize, here is the declaration

```
<GridTable
  columns={columns}
  onRowsRequest={onRowsRequest}
  onLoad={setTableManager}
  pageSize={10}
  pageSizes={[10, 25, 50]}
  selectAllMode="page"
/>
```

after your mention, I also added 

```
<GridTable
  columns={columns}
  onRowsRequest={onRowsRequest}
  onLoad={setTableManager}
  pageSize={10}
  pageSizes={[10, 25, 50]}
  batchSize={10}
  selectAllMode="page"
/>
```

still didn't make any difference

**Comment by kringo** [comment]
Any updates would be helpful, thanks.

**Comment by NadavShaar** [comment]
Is there a way you can create a simple example showing the issue in a CodeSandbox so we can see it?

**Comment by kringo** [comment]
Thanks for your reply. This happens with a very basic example of a grid with onRowsRequest talking to an api endpoint, if you have a local api setup pls try it out.

Meanwhile, I haven't used codesandbox, let me see if i can create a quick example.

**Comment by kringo** [comment]
Threw in a quick example: https://codesandbox.io/s/nadavshaar-react-grid-ft90r

Check the network / xhr inside dev tools, you'll notice 2 subsequent calls to the endpoint

Hope this helps

**Comment by NadavShaar** [comment]
Thanks, we'll investigate the issue.

**Comment by kringo** [comment]
🙏

**Comment by NadavShaar** [comment]
Fixed in `v1.0.1 please verify that the issue was fixed.

**Comment by kringo** [comment]
Just tried, didn't see any difference. Am i missing anything?

**Comment by NadavShaar** [comment]
No there was a build issue in `v1.0.1` please install `v1.0.2` instead.

**Comment by kringo** [comment]
Yes, that did it & works like a charm. 🙏  a lot!

**Comment by NadavShaar** [comment]
No problem thank you for reporting the issue :)
