### ISSUE TITLE
I want search functionality as an individual column is it possible? 

### ISSUE THREAD

**Issue by dropways** [NadavShaar/react-grid-table#81]
Like this!

![image](https://user-images.githubusercontent.com/38377336/142156921-eee9ba6e-9bef-490d-aff1-c1cc7608a093.png)

Is it possible to do?

**Comment by NadavShaar** [comment]
You should be able to use `headerCellRenderer` in the column config to create your own custom header cell and add this component and functionality as part of it.
Hope it helps :)
