### ISSUE TITLE
Dots logic when resize 

### ISSUE THREAD

**Issue by stevenKirill** [NadavShaar/react-grid-table#83]
Hello! Can I ask you question about how did you make the logic when you resize column and then three dots appear and title become half hidden? I can't fins the answer, I would like to create kinda same scenario, I would be thankful if you can answer me
<img width="604" alt="redize" src="https://user-images.githubusercontent.com/47239173/146163822-9de28418-bc49-4fd6-af1b-870a670848b2.png">

**Comment by NadavShaar** [comment]
Created a small example for it, hope it helps
https://codesandbox.io/s/column-resize-sfws4?file=/index.html

**Comment by stevenKirill** [comment]
thank you very much my friend
