### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by dukesx** [NadavShaar/react-grid-table#84]
Trying to use it inside Next Js but unable to get it loaded. Help Please. 

Using: V1.0.2

Note: if i load it dynamically , it does render but then it only shows data. I mean, you cant interact with it. 

If i try to resize column, it will resize a few pixel and return to original size,  it acts as if it is stuck in a loop of infinite state updates. i cant press drop down , i basically cant interact. if i click drop down of table, imagine as if i toggle state from true to false, and false to truth every second, thats the kind of behavior i am seeing. 

console error shows: 
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

Further debugging: 

The issue is from onRowsRequest,  i am using "controlled" async approach
```ts
async (requestData, tableManager) => {
              const { data, error } = await supabase.from("table_name").select();

              if (error != null) {
                return;
              } else {
                return {
                  rows: data,
                  totalRows: data.length,
                };
              }
```

if i remove the async method and just return plain static data inside this function, table remains normal, but if promise gets involved, table starts to react abnormal as i have described above.

**Comment by NadavShaar** [comment]
Hi, sorry to hear that you're having issues, having that said, it is hard to debug a specific case like yours without having the code, can you create and share a live example showing that issue please?

**Comment by dukesx** [comment]
Sure , let me do it

**Comment by dukesx** [comment]
this is the repo

**Comment by dukesx** [comment]
#### Look at the hover state of the "three dots" of table. see the difference when i hover over my name and when i hover over the three dots. 

#### Next see when i resize the columns. How they reset to their original size, they wont change their size



https://user-images.githubusercontent.com/5988991/146981436-b08d513c-c0e1-4436-945c-75ef3883fbf9.mp4

**Comment by dukesx** [comment]
You will see in the code , /pages/admin/article/index.tsx , that i am using Next JS's dynamic module. If i change option from SSR to true inside its option, you will see the error "Self is NOT defined"

**Comment by dukesx** [comment]
### Update
Fault is aligning for me if i use 

```js
           rows={rows}
            onRowsChange={setRows}
            totalRows={totalRows}
            onTotalRowsChange={setTotalRows}

```
with onRowsRequest. If i use the setTimeOut way of doing this, it works fine but for real world api fetches ? Not so much. Atleast not for me. I will try with mock api too

**Comment by NadavShaar** [comment]
Hi again, i meant that you create a clean working example in Next.js environment so we can rule out something else in your project is causing the issue, but no worries i did it myself.

So after some investigation regarding the `ReferenceError: self is not defined` i found this: https://stackoverflow.com/questions/66096260/why-am-i-getting-referenceerror-self-is-not-defined-when-i-import-a-client-side which explain that the server is trying to access the `window` object which is not available there, only in the browser, and as the answer suggests, you should load the table dynamically with the `ssr` option set to false.
I created a simple working example here: https://www.anyfiddle.com/p/nadavshaar/nnzfnhqm you'll see that there's one file containing the table component `MyAwesomeTable.js` without rendering it, and a file `index.js` which loads it dynamically with `ssr: false` and rendering it.

Hope it helps :)

**Comment by NadavShaar** [comment]
Regarding those other issues you're mentioning please try to recreate them in a fiddle like i sent, i can't run your project.

**Comment by NadavShaar** [comment]
Regarding those blinking issues and columns resetting, If i need to guess, it's because they are defined in the render, try putting them outside of the component scope or at least on the state.

**Comment by dukesx** [comment]
@NadavShaar  now check the fiddle : https://www.anyfiddle.com/p/uthreviews/jk9nai74

**Comment by dukesx** [comment]
we will have to check with supabase, mock api seems to work fine with it. For some reason, supabase javascript client is causing this otherwise i have "some" successful tries with mock api where table doesnt go inside state loop. Fiddle seems to be completely fine. Unable to reproduce it at that end. i will try to create a replica of my own setup with example supabase project

**Comment by NadavShaar** [comment]
OK, so i'm closing the issue, for now, feel free to open a new one if needed... good luck!
