### ISSUE TITLE
Cannot find module: '@nadavshaar/react-grid-table/dist/index.css'

### ISSUE THREAD

**Issue by shrutikkharkar** [NadavShaar/react-grid-table#86]
index.css is not available downloading using npm command

**Comment by NadavShaar** [comment]
Hi, can you please specify the steps you did that cause this message?

**Comment by shrutikkharkar** [comment]
Index.css is not getting downloaded while we do npm install. I had to
manually download this file from your GitHub account and put it in node
modules. And the specified issue occurred when I tried to deploy the app on
heroku.

**Comment by NadavShaar** [comment]
It's a bit hard to know what is going on in your project since I don't have the code, please create a live example on CodeSandbox or where ever you prefer, to demonstrate your issue and share it so I'll be able to debug the issue... thanks.

**Comment by shrutikkharkar** [comment]
Issue solved! Thanks
