### ISSUE TITLE
Using Grid in flex layout causing headers not to resize

### ISSUE THREAD

**Issue by AinsworthDevelopment** [NadavShaar/react-grid-table#87]
Hi @NadavShaar 

I am trying to use the grid in a flex layout, but the headers are now unable to be resized

I have recreated an example using the Demo adding a sidebar and a flex container

https://codesandbox.io/s/currying-leftpad-rs9z19?file=/src/App.js

**Comment by NadavShaar** [comment]
You had some issues in the example, now it's working:
https://codesandbox.io/s/cool-hooks-8x1x2r?file=/src/App.js

**Comment by AinsworthDevelopment** [comment]
Thanks for the help
