### ISSUE TITLE
defaultValue or defaultChecked stop columns sorting

### ISSUE THREAD

**Issue by passariello** [NadavShaar/react-grid-table#90]
Hi man!,
I don't know why but when I use cellRenderer with input and defaultValue or defaultChecked the sorting stop to works... some columns works but not where is present a cellRender with this setup. If I remove they works properly an I can sort again.
My goal is to have custom checkbox, input date and input text ( all customized directly using html )... My way is more simple and not require tons of call back. It's works with data, onclicks events in general and are really very easy to manage... but I incurred into this issue. Can you help me to figure out a way?

It's an example:

      id: 3,
      visible: true,
      resizable: true,
      field: 'active',
      label: 'Active',
      width: "90px",
      //sortable: false,
      className: styles.centerText,
      cellRenderer: ({ value, data, column }) => {
        return (
        <input
          id={`product[${column.field}]`}
          name={`product[${column.field}]`}
          type="checkbox"
          row-id={ data.product_id }
          defaultChecked={ value == -1 ? true : false }
          onInput={ (e)=> onInputProd( 2, [ data.product_id, props ], e ) }
          onChange={ onChange }
        />
      )}

![Screenshot 2022-05-10 233427](https://user-images.githubusercontent.com/17809213/167776067-91451a64-bbdd-4d78-bc4d-b7d757c39d78.png)

![Screenshot 2022-05-10 233623](https://user-images.githubusercontent.com/17809213/167776265-17e66e67-7f53-4522-9945-b2735fe046b5.png)

**Comment by NadavShaar** [comment]
Hi, I'm not sure what you're trying to achieve here, are you trying to sort a column made out of checkbox only?

**Comment by NadavShaar** [comment]
Also, if you can recreate a basic live example of the issue you're facing in a codesandbox or something it will be much easier and faster to find the problem... Thanks

**Comment by NadavShaar** [comment]
Since you're not responding can i assume that you got it fixed? let me know if I can close this issue...
