### ISSUE TITLE
selectedRowsIds does not update after data update

### ISSUE THREAD

**Issue by zichAtIP** [NadavShaar/react-grid-table#91]
Hi!

I'm using your component and I use row selection to bulk delete rows.
I might be wrong here, but it seems as though selectedRowsIds does not update after some data is deleted from the data set the rows prop is connected to.

### How to recreate:
1. Select some rows (say 3 for example)
2. Delete those rows, set the rows state afterwards 
3. Voila! The rows are deleted from the table but the selected rows counter still displays 3 (and selectedRowsIds still holds the deleted rows)

Cheers!

**Comment by NadavShaar** [comment]
Hi, thanks for reporting this issue, can you please recreate this issue in a live example like in codesandbox or something?

**Comment by NadavShaar** [comment]
We are working on a fix.

**Comment by NadavShaar** [comment]
Still working on a possible fix, for now you can clear the selected rows manually if the delete action was successful using:
`tableManager.rowSelectionApi.setSelectedRowsIds([])`

**Comment by NadavShaar** [comment]
Fixed in V1.1.0
