### ISSUE TITLE
Compatibility issue with react@18.2.0

### ISSUE THREAD

**Issue by VivekTodur** [NadavShaar/react-grid-table#95]
Hi @NadavShaar,

I am getting the following error, could you please help me to fix this?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ui@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from @nadavshaar/react-grid-table@1.0.2
npm ERR! node_modules/@nadavshaar/react-grid-table
npm ERR!   @nadavshaar/react-grid-table@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry

**Comment by NadavShaar** [comment]
Hi, after testing react 18.2 support, it seems to be working, did you manage to find the problem?
https://codesandbox.io/s/nadavshaar-react-grid-table-react-18-2-test-zm9mkx

**Comment by NadavShaar** [comment]
Closing. feel free to reopen if the issue still exists.

**Comment by VivekTodur** [comment]
No, it still the same. I have tried with the fresh project as well without loading any other module, but error remains same. I am using NodeJS v18.9.1, ReactJS v18.2.0

**Comment by VivekTodur** [comment]
Downgrading ReactJS to stable version 16.70 and install the package via "npm i "@nadavshaar/react-grid-table" --force" allowed me to run the application, will test it further and post if I see more hurdles. Thank you so much @NadavShaar .

**Comment by NadavShaar** [comment]
Thanks, please let me know about your findings, and if you can share this issue in a live sand box like i did I'll be able to try and help.

**Comment by NadavShaar** [comment]
Fixed in V1.1.0
