### ISSUE TITLE
Deleting Rows

### ISSUE THREAD

**Issue by pan-alex** [NadavShaar/react-grid-table#98]
Hello, I'm wondering if there is a feature to delete rows?

Intuitively, I thought that selecting a row and clicking the garbage bin would delete the selected row. However, I've learned that this just clears the selection.

I've played with the demo and read through the docs but maybe I've missed something.

**Comment by NadavShaar** [comment]
Deleting rows is done outside the table, you're getting the selected rows' ids that you can use to delete the relevant data.

**Comment by pan-alex** [comment]
Thanks for the quick response. I was able to implement a way to delete rows using the selected rows' ids.

I do find it surprising that there isn't a way to delete rows from inside of the table, given how fully featured this table is. 

The garbage bin does feel a bit redundant as the checkbox in the top-left is the most intuitive way to clear the selection (for me, anyway). Are there any plans to add a feature to delete rows from inside the table (even as an optional config parameter)?

In any case, appreciate all the work on this component. It has some really impressive features and great docs/demos.
